In [1]:
import torch 

In [10]:
inputs = torch.tensor([[0.43, 0.15, 0.89],
                      [0.55, 0.87, 0.66],
                      [0.57, 0.85, 0.64],
                      [0.22, 0.58, 0.33],
                      [0.77, 0.25, 0.10],
                      [0.05, 0.80, 0.55]

])

In [15]:
dot_product_array = torch.zeros(6,6)
for i in range(len(inputs)):
    for j in range(len(inputs)):

        print(torch.dot(inputs[i], inputs[j]))
        dot_product_array[i][j] = torch.dot(inputs[i], inputs[j])

tensor(0.9995)
tensor(0.9544)
tensor(0.9422)
tensor(0.4753)
tensor(0.4576)
tensor(0.6310)
tensor(0.9544)
tensor(1.4950)
tensor(1.4754)
tensor(0.8434)
tensor(0.7070)
tensor(1.0865)
tensor(0.9422)
tensor(1.4754)
tensor(1.4570)
tensor(0.8296)
tensor(0.7154)
tensor(1.0605)
tensor(0.4753)
tensor(0.8434)
tensor(0.8296)
tensor(0.4937)
tensor(0.3474)
tensor(0.6565)
tensor(0.4576)
tensor(0.7070)
tensor(0.7154)
tensor(0.3474)
tensor(0.6654)
tensor(0.2935)
tensor(0.6310)
tensor(1.0865)
tensor(1.0605)
tensor(0.6565)
tensor(0.2935)
tensor(0.9450)


In [16]:
dot_product_array

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [20]:
dot_product_array
for i, row in enumerate(dot_product_array):
    dot_product_array[i] = torch.softmax(dot_product_array[i], dim =0)

In [21]:
dot_product_array

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [29]:
dot_product_array @ inputs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [30]:
for i in range(len(inputs)):
    for j in range(len(inputs)):
        print(dot_product_array[i]@inputs[:, :j])

tensor([])
tensor([0.4421])
tensor([0.4421, 0.5931])
tensor([0.4421, 0.5931, 0.5790])
tensor([0.4421, 0.5931, 0.5790])
tensor([0.4421, 0.5931, 0.5790])
tensor([])
tensor([0.4419])
tensor([0.4419, 0.6515])
tensor([0.4419, 0.6515, 0.5683])
tensor([0.4419, 0.6515, 0.5683])
tensor([0.4419, 0.6515, 0.5683])
tensor([])
tensor([0.4431])
tensor([0.4431, 0.6496])
tensor([0.4431, 0.6496, 0.5671])
tensor([0.4431, 0.6496, 0.5671])
tensor([0.4431, 0.6496, 0.5671])
tensor([])
tensor([0.4304])
tensor([0.4304, 0.6298])
tensor([0.4304, 0.6298, 0.5510])
tensor([0.4304, 0.6298, 0.5510])
tensor([0.4304, 0.6298, 0.5510])
tensor([])
tensor([0.4671])
tensor([0.4671, 0.5910])
tensor([0.4671, 0.5910, 0.5266])
tensor([0.4671, 0.5910, 0.5266])
tensor([0.4671, 0.5910, 0.5266])
tensor([])
tensor([0.4177])
tensor([0.4177, 0.6503])
tensor([0.4177, 0.6503, 0.5645])
tensor([0.4177, 0.6503, 0.5645])
tensor([0.4177, 0.6503, 0.5645])


In [43]:
inputs = torch.tensor([
    [0.2, 0.1, 0.3],  # I
    [0.7, 0.3, 0.5],  # bank (verb)
    [0.1, 0.2, 0.2],  # the
    [0.8, 0.4, 0.6],  # firewood
    [0.3, 0.4, 0.3],  # by
    [0.1, 0.2, 0.2],  # the
    [0.6, 0.5, 0.7],  # river
    [0.7, 0.3, 0.5],  # bank (noun)
])

In [44]:
dot_product_array = torch.zeros(len(inputs),len(inputs))
for i in range(len(inputs)):
    for j in range(len(inputs)):

        print(torch.dot(inputs[i], inputs[j]))
        dot_product_array[i][j] = torch.dot(inputs[i], inputs[j])

tensor(0.1400)
tensor(0.3200)
tensor(0.1000)
tensor(0.3800)
tensor(0.1900)
tensor(0.1000)
tensor(0.3800)
tensor(0.3200)
tensor(0.3200)
tensor(0.8300)
tensor(0.2300)
tensor(0.9800)
tensor(0.4800)
tensor(0.2300)
tensor(0.9200)
tensor(0.8300)
tensor(0.1000)
tensor(0.2300)
tensor(0.0900)
tensor(0.2800)
tensor(0.1700)
tensor(0.0900)
tensor(0.3000)
tensor(0.2300)
tensor(0.3800)
tensor(0.9800)
tensor(0.2800)
tensor(1.1600)
tensor(0.5800)
tensor(0.2800)
tensor(1.1000)
tensor(0.9800)
tensor(0.1900)
tensor(0.4800)
tensor(0.1700)
tensor(0.5800)
tensor(0.3400)
tensor(0.1700)
tensor(0.5900)
tensor(0.4800)
tensor(0.1000)
tensor(0.2300)
tensor(0.0900)
tensor(0.2800)
tensor(0.1700)
tensor(0.0900)
tensor(0.3000)
tensor(0.2300)
tensor(0.3800)
tensor(0.9200)
tensor(0.3000)
tensor(1.1000)
tensor(0.5900)
tensor(0.3000)
tensor(1.1000)
tensor(0.9200)
tensor(0.3200)
tensor(0.8300)
tensor(0.2300)
tensor(0.9800)
tensor(0.4800)
tensor(0.2300)
tensor(0.9200)
tensor(0.8300)


In [45]:
dot_product_array

tensor([[0.1400, 0.3200, 0.1000, 0.3800, 0.1900, 0.1000, 0.3800, 0.3200],
        [0.3200, 0.8300, 0.2300, 0.9800, 0.4800, 0.2300, 0.9200, 0.8300],
        [0.1000, 0.2300, 0.0900, 0.2800, 0.1700, 0.0900, 0.3000, 0.2300],
        [0.3800, 0.9800, 0.2800, 1.1600, 0.5800, 0.2800, 1.1000, 0.9800],
        [0.1900, 0.4800, 0.1700, 0.5800, 0.3400, 0.1700, 0.5900, 0.4800],
        [0.1000, 0.2300, 0.0900, 0.2800, 0.1700, 0.0900, 0.3000, 0.2300],
        [0.3800, 0.9200, 0.3000, 1.1000, 0.5900, 0.3000, 1.1000, 0.9200],
        [0.3200, 0.8300, 0.2300, 0.9800, 0.4800, 0.2300, 0.9200, 0.8300]])

In [36]:
dot_product_array
for i, row in enumerate(dot_product_array):
    dot_product_array[i] = torch.softmax(dot_product_array[i], dim =0)

In [37]:
dot_product_array

tensor([[0.1122, 0.1344, 0.1078, 0.1427, 0.1180, 0.1078, 0.1427, 0.1344],
        [0.0902, 0.1502, 0.0824, 0.1745, 0.1058, 0.0824, 0.1643, 0.1502],
        [0.1143, 0.1302, 0.1132, 0.1368, 0.1226, 0.1132, 0.1396, 0.1302],
        [0.0840, 0.1530, 0.0760, 0.1831, 0.1025, 0.0760, 0.1725, 0.1530],
        [0.1024, 0.1369, 0.1004, 0.1513, 0.1190, 0.1004, 0.1528, 0.1369],
        [0.1143, 0.1302, 0.1132, 0.1368, 0.1226, 0.1132, 0.1396, 0.1302],
        [0.0861, 0.1477, 0.0794, 0.1768, 0.1062, 0.0794, 0.1768, 0.1477],
        [0.0902, 0.1502, 0.0824, 0.1745, 0.1058, 0.0824, 0.1643, 0.1502]])

In [39]:
sentence = "I bank the firewood by the river bank"
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("slauw87/bart_summarisation")

tokenizer_config.json:   0%|          | 0.00/300 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.63k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [41]:
tokens = tokenizer(text = sentence, padding = False, truncation = False,
                   max_length = 8, stride =0)

In [42]:
tokens


{'input_ids': [0, 100, 827, 5, 668, 1845, 30, 5, 4908, 827, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}